name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: aryan19801
          outputs: |
            dist/github-contribution-grid-snake.svg
          # 👇👇 Customize appearance
          color_snake: "#39FF14"      # bright neon green snake
          color_dots: "#0A0F0D,#39FF14,#0A0F0D,#39FF14"  # dark background with bright contrast dots
          svg_output_width: 800       # wider canvas

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
